services:
  app:
    build:
      context: .
      dockerfile: Dockerfile
      args:
        - NODE_ENV=${NODE_ENV} # Pass NODE_ENV during build
    env_file:
      - .env.${NODE_ENV}  # Load the appropriate .env file
    ports:
      - '3000:3000'
    command: >
      sh -c "if [ '${NODE_ENV}' = 'development' ]; then bun run dev; else bun run start; fi"
    #  Volumes (uncomment for development ONLY):
    # volumes:
    #   - .:/app
    #   - /app/node_modules 