version: '3.8'  # Updated version for Docker Compose

services:
  app:
    build: .
    ports:
      - '3001:3001'
    environment:
      - NODE_ENV=development
      - PORT=3001
    volumes:
      - .:/app
      - /app/node_modules
    command: ["bun", "run", "dev"]